-- Find total customers by countries
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT
category,
COUNT(product_key) AS total_product
FROM gold.dim_products
GROUP BY category
ORDER BY total_product DESC

-- What is the average costs in each category?
SELECT
category,
AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category?

SELECT
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key=p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Find total revenue is generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) AS sales_per_customer
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key=c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY sales_per_customer DESC

-- What is the distribution of sold items across countries?
SELECT
c.country,
SUM(s.quantity) AS total_sold_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key=c.customer_key
GROUP BY 
c.country
ORDER BY total_sold_items DESC